version:  '3'
services:
  base-notebook:
      image: conda/miniconda2
      user: root
      build: .
      volumes:
        - /home/felix/KID_scripts:/home/KID/KID_scripts
      container_name: PyASB
      command: "tail -f /dev/null"